{
 "title": "Monitor-wallets",
 "description": "OTC",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "ethereum",
    "query": {
     "query": "label_values(wallet_balance{network=\"$ethereum\"},network)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "History-ETH",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "wallet_balance{network=\"sepolia\", token=\"ETH\", wallet=~\"Wallet-1|Wallet-2|Wallet-3|Wallet-4|Wallet-5\"}",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "History-SOL",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "wallet_balance{network=\"sol-devnet\", token=\"SOL\"}",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "History-USDC-Evm",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "wallet_balance{network=\"sepolia\", token=\"USDC\", wallet=~\"Wallet-1|Wallet-2|Wallet-3|Wallet-4|Wallet-5\"}",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "History-USDC-Svm",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "wallet_balance{network=\"sol-devnet\", token=\"USDC\"}",
     "legendFormat": "{{tag}}"
    }
   ]
  },
  {
   "title": "System wallets",
   "type": "table",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "wallet_balance{network=\"sepolia\", wallet!~\"MM1|MM3|MM2|MM5|MM4\"}",
     "legendFormat": "{{token}}"
    }
   ]
  },
  {
   "title": "System wallets SVM",
   "type": "table",
   "gridPos": { "h": 27, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "wallet_balance{network=\"sol-devnet\", wallet!~\"MM1|MM2|MM3\"}",
     "legendFormat": "{{token}}"
    }
   ]
  }
 ]
}